ancestrywebsite/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name="accounts"
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),


    #Django Auth
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name="logout")
    ]

ancestrywebsite/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name="contact"
urlpatterns = [
    path("", contact, name="contact")
    ]

ancestrywebsite/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ancestrywebsite.apps.public.urls')),
    path('accounts/', include('ancestrywebsite.apps.accounts.urls')),
    path('contact/', include('ancestrywebsite.apps.contact.urls')),
    ]

ancestrywebsite/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    is_full_name_displayed = models.BooleanField(default=True)

    #Ancestry Information
    info = models.CharField(max_length=1000, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)

    #contact details
    emailaddress = models.EmailField(max_length=250, default="default_email")
    phone_number = PhoneNumberField(blank=True)

ancestrywebsite/apps/contact/models.py
from django.db import models

# Create your models here.

ancestrywebsite/apps/contact/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : "Name"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : "Email"}))
    phonenumber = PhoneNumberField(required=False, widget=PhoneNumberPrefixWidget(attrs={'class' : 'form-control', 'placeholder' : "Phone number"}))
    message = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : "Message", "rows": 5}))

ancestrywebsite/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin




class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

ancestrywebsite/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail

from ancestrywebsite import settings

from .forms import ContactForm


def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            message = bleach.clean(form.cleaned_data["message"])
            email = bleach.clean(form.cleaned_data["email"])
            phonenumber = form.cleaned_data["phonenumber"]
            send_mail(f"{name} sent an email.", f"{message}. Number: {phonenumber}", email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, 'contact.html', {"form": form, "success": True})
    else:
        raise NotImplementedError
    
    return render(request, 'contact.html', {"form": form})

ancestrywebsite/templates/about.html
{% extends 'base.html' %}

{% block title %}About Royal Ancestry{% endblock %}

{% block content %}
<h1>
    About Royal Ancestry
</h1>

<p class="text-white-50">
    Royal Ancestry is an independent geneaology business based in Newcastle upon Tyne and ran by Ian Royal, 
    <br>
    a family tree enthusiast with decades of 
    experience researching his own, and other family trees.
    <br>
    <br>
    Offering a bespoke, personal, service, we can help you unlock your family history.
</p>
{% endblock %}

ancestrywebsite/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Login</button>
</form>
{% endblock %}

ancestrywebsite/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Your Profile{% endblock %}

{% block content %}

<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <div>
            <h3>
            Contact Details:           
            </h3>
            Email: {{profile.emailaddress|default:""}}
            <br/>
            Phone Number: {{profile.phonenumber|default:"No phone number provided"}}
        </div>
        <br/>
        <div>
            <h3>
            Ancestry Details:
            </h3>
            {{profile.info|default:"info"}}
        </div>
    {% endif %}
{% endwith %}


{% endblock %}

ancestrywebsite/templates/base.html
{% load static %}
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  {{ form.media.css }}
  <meta charset="utf-8">
  <title>{% block title %}Royal Ancestry{% endblock %}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'theme/css/styles.css'%}" rel="stylesheet" />

  <link href="{% static 'css/main.css'%}" rel="stylesheet" />
</head>


<body>
  <main id="main">
    {% block content %}
    
    {% endblock %}
  </main>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
{% include 'navbar.html' %}
</html>

ancestrywebsite/templates/blog.html
{% extends 'base.html' %}

{% block title %}Royal Ancestry Blog{% endblock %}

{% block content %}
<h1>
    Testimonials/Blog
</h1>

<p class="text-white-50">
    All your amazing testimonials
</p>

{% endblock %}

ancestrywebsite/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}

<section class="page-section" id="contact">
    <div class="container">
    <!-- Contact Section Heading -->
    <h1> Contact us: </h1>
    <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
            <div class="divider-custom-line"></div>
        </div>
    
        <div class="text-center text-secondary mb-0">
            <p class="text-white-50">
                Drop us a message expressing your interest using the form below.
            </p>
            <p class="text-white-50">
                Alternatively, send us an email at <a href="mailto:ianroyalancestry@gmail.com">ianroyalancestry@gmail.com</a>
            </p>
        </div>

                <!-- Contact Section Form -->
        <div class="row">
            <div class ="col-lg-8 mx-auto">

                {% if success %}
                <div class="alert alert-success" role="alert">
                    Your message has been sent! We'll be in touch soon.
                </div>
                {% endif %}


                <form id="contactForm" name="sentMessage" novalidate="novalidate" method="post">
                    {% csrf_token %}


                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.nonfield_errors}}
                    </div>
                    {% endif %}
                    
                    {% for field in form %}
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label class="text-white-50">{{ field.label_tag }}</label>
                            {{ field }}

                            {% for error in field.errors %}
                            <p class="help-block text-danger text-red-50">{{error}}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <br />
                    <div class="form-group"><button class="btn hs-bg-primary btn-xl" id="sendMessageButton" type="submit">Send</button></div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ancestrywebsite/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Royal Ancestry{% endblock %}

{% block content %}
<h1>
    Welcome to Royal Ancestry
</h1>

<p class="text-white-50 home-text">
    Hi! I'm Ian Royal. I run Royal Ancestry, where you can uncover your past and the lives of your ancestors.
    <br>
    Let me help to bring your family history to life. 
</p>

<div>
    <img id="ian" src="static/theme/assets/img/ian.jpg" alt="Ian Royal">
</div>

{% endblock %}

ancestrywebsite/templates/navbar.html
{% url 'public:index' as index_url %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{{ index_url }}">Royal Ancestry</a>
        <div id="logo">
            <img id="tree" src=..\static\theme\assets\img\tree.png>
        </div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% url 'public:index' as index_url %}
                <li class="nav-item"><a class="nav-link {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                {% url 'public:about' as about_url %}
                <li class="nav-item"><a class="nav-link {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                {% url 'contact:contact' as contact_url %}
                <li class="nav-item"><a class="nav-link {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                {% url 'public:blog' as blog_url %}
                <li class="nav-item"><a class="nav-link {% if request.path == blog_url %}active{% endif %}" href="{{ blog_url }}">Blog</a></li>
                    {% if user.is_authenticated %}  
                        {% url 'accounts:profile' as profile_url %} 
                        <li class="nav-item"><a class="nav-link {% if request.path == profile_url %}active{% endif %}" href="{{profile_url}}">Profile</a></li>
                        {% url 'accounts:logout' as logout_url %}
                        <li class="nav-item"><a class="nav-link {% if request.path == logout_url %}active{% endif %}" href="{{logout_url}}">Logout</a></li>
                    {% else %}  
                        {% url 'accounts:login' as login_url %}
                        <li class="nav-item"><a class="nav-link {% if request.path == logout_url %}active{% endif %}" href="{{login_url}}">Login</a></li>
                    {% endif %} 
            </ul>
        </div>
    </div>
</nav>

<!--
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'public:blog' as blog_url %}
    <span>{% if request.path == blog_url %}Blog{% else %}<a href="{{ blog_url }}">Blog</a>{% endif %}</span>
    {% url 'contact:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span>Hi {% if request.path == profile_url %}{{user.username}}{% else %}<a href="{{profile_url}}">{{user.username}}</a>{% endif %}!</span>
            <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}
    </span>
</nav>
-->